spring:
    application:
    name: touceng_finance
    profiles:
      active: dev
#==================== 日志  ============================
logging: 
  config: classpath:logback.xml

# mybatis 配置        
mybatis:
    mapperLocations: classpath*:mapper/*.xml
    typeAliasesPackage: com.touceng.**.mapper

##mybatis 分页
pagehelper:
    helperDialect: mysql
    reasonable: false
    supportMethodsArguments: true